"""
preview_html.py — Generate and serve a MkDocs static site from the converted Markdown output.

Reads _toc.json files produced by Step 6, builds a MkDocs nav, writes preview/mkdocs.yml
and a hook script that renders YAML frontmatter as a styled info block, then runs
mkdocs serve (default) or mkdocs build.

Usage:
  python scripts/preview_html.py                                      # serve all products
  python scripts/preview_html.py --product businessevents-enterprise  # one product
  python scripts/preview_html.py --product bwce --version 2.9.2       # one version
  python scripts/preview_html.py --build                              # static build only
  python scripts/preview_html.py --help
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Hook script source — written verbatim to preview/hooks/frontmatter_display.py
# ---------------------------------------------------------------------------

_HOOK_SOURCE = '''\
"""
frontmatter_display.py — MkDocs hook: render YAML frontmatter as an info admonition.
Auto-generated by scripts/preview_html.py — do not edit manually.
"""

import yaml


def on_page_markdown(markdown, page, config, files):
    """Prepend a Material admonition block showing YAML frontmatter metadata."""
    if not markdown.startswith("---"):
        return markdown

    end = markdown.find("\\n---\\n", 3)
    if end == -1:
        return markdown

    raw_fm = markdown[3:end].strip()
    body = markdown[end + 5:]

    try:
        fm = yaml.safe_load(raw_fm)
    except Exception:
        return markdown

    if not isinstance(fm, dict):
        return markdown

    lines = ["!!! info \\"Page Metadata\\""]

    product = fm.get("product_name", "")
    version = fm.get("product_version", "")
    if product or version:
        lines.append(f"    **Product:** {product} {version}".rstrip())

    doc_name = fm.get("doc_name", "")
    if doc_name:
        lines.append(f"    **Doc:** {doc_name}")

    topic_type = fm.get("topic_type", "")
    lang = fm.get("lang", "")
    if topic_type or lang:
        parts = []
        if topic_type:
            parts.append(f"Type: *{topic_type}*")
        if lang:
            parts.append(f"Language: {lang}")
        lines.append("    **" + "** &nbsp;|&nbsp; **".join(parts) + "**")

    toc_path = fm.get("toc_path", "")
    if toc_path:
        # Strip any remaining MadCap variable tokens and replace pipe separator
        import re
        toc_path = re.sub(r"\\[%=.*?%\\]", "", toc_path).strip()
        toc_path = toc_path.replace("|", " › ")
        lines.append(f"    **TOC:** {toc_path}")

    source_url = fm.get("source_url", "")
    if source_url:
        lines.append(f"    **Source:** <{source_url}>")

    csh_ids = fm.get("csh_ids", [])
    csh_names = fm.get("csh_names", [])
    if csh_ids:
        id_str = ", ".join(str(i) for i in csh_ids)
        name_str = ", ".join(str(n) for n in csh_names) if csh_names else ""
        csh_line = f"    **CSH IDs:** {id_str}"
        if name_str:
            csh_line += f"  *(Names: {name_str})*"
        lines.append(csh_line)

    admonition = "\\n".join(lines) + "\\n\\n"
    return admonition + body
'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_mkdocs_exe(override: str | None = None) -> str:
    """Return path to mkdocs executable, or exit with install instructions."""
    if override:
        return override

    found = shutil.which("mkdocs")
    if found:
        return found

    # Try next to the current Python interpreter (same venv / Scripts dir)
    candidate = Path(sys.executable).parent / "mkdocs"
    if candidate.exists():
        return str(candidate)
    candidate_exe = Path(sys.executable).parent / "mkdocs.exe"
    if candidate_exe.exists():
        return str(candidate_exe)

    print(
        "\nERROR: mkdocs not found.\n"
        "Install it with:\n"
        "  pip install mkdocs mkdocs-material\n",
        file=sys.stderr,
    )
    sys.exit(1)


def discover_toc_files(
    output_dir: Path,
    products: list[str],
    version: str | None,
) -> list[Path]:
    """Return sorted list of _toc.json paths matching the given filters."""
    all_tocs = sorted(output_dir.rglob("_toc.json"))

    if not products and not version:
        return all_tocs

    filtered = []
    for toc in all_tocs:
        rel = toc.relative_to(output_dir).as_posix()  # e.g. pub/bwce/2.9.2/doc/html/_toc.json
        parts = rel.split("/")
        # parts[0] == "pub", parts[1] == product-slug, parts[2] == version
        if len(parts) < 3:
            filtered.append(toc)
            continue
        slug = parts[1]
        ver = parts[2]
        if products and not any(p.lower() in slug.lower() for p in products):
            continue
        if version and version != ver:
            continue
        filtered.append(toc)

    return filtered


def _norm(path_str: str) -> str:
    """Normalise Windows backslashes to forward slashes."""
    return path_str.replace("\\", "/")


def toc_node_to_nav(node: dict, output_dir: Path) -> dict | None:
    """
    Recursively convert a _toc.json tree node to a MkDocs nav entry.
    Returns None if the node has no file and no valid children.
    """
    title = node.get("title", "Untitled")
    file_raw = node.get("file")
    children = node.get("children", [])

    # Build child nav entries first
    child_nav = []
    for child in children:
        entry = toc_node_to_nav(child, output_dir)
        if entry is not None:
            child_nav.append(entry)

    if file_raw:
        file_path = _norm(file_raw)
        # Verify the file exists on disk
        if not (output_dir / file_path).exists():
            # Still include children if any
            if child_nav:
                return {title: child_nav}
            return None
        if child_nav:
            # Page + children: include the page as first child
            return {title: [{title: file_path}] + child_nav}
        else:
            return {title: file_path}
    else:
        # Section-only node (no file)
        if child_nav:
            return {title: child_nav}
        return None


def build_nav_from_tocs(toc_files: list[Path], output_dir: Path) -> list[dict]:
    """
    Read each _toc.json and build the top-level MkDocs nav list.
    Each version appears as a top-level nav group labelled by its version string.
    """
    nav = []
    missing_files = 0

    for toc_path in toc_files:
        try:
            data = json.loads(toc_path.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"  WARNING: Could not read {toc_path}: {exc}", file=sys.stderr)
            continue

        version_label = data.get("version", str(toc_path.parent))
        tree = data.get("tree", [])
        orphans = data.get("_orphans", [])

        version_nav = []
        for node in tree:
            entry = toc_node_to_nav(node, output_dir)
            if entry is not None:
                version_nav.append(entry)

        # Append orphan pages as a flat section at the bottom
        if orphans:
            orphan_entries = []
            for orphan in orphans:
                orphan_title = orphan.get("title", Path(orphan.get("file", "?")).stem)
                orphan_file = _norm(orphan.get("file", ""))
                if orphan_file and (output_dir / orphan_file).exists():
                    orphan_entries.append({orphan_title: orphan_file})
            if orphan_entries:
                version_nav.append({"Orphaned Pages": orphan_entries})

        if version_nav:
            nav.append({version_label: version_nav})

    if missing_files:
        print(f"  NOTE: {missing_files} nav entries skipped (file not found on disk)")

    return nav


def build_nav_from_filesystem(output_dir: Path, products: list[str], version: str | None) -> list[dict]:
    """
    Fallback nav builder when no _toc.json files exist (Step 6 not yet run).
    Groups .md files by product/version directory as flat sections.
    """
    print(
        "  WARNING: No _toc.json files found. Building flat nav from filesystem.\n"
        "  Run Step 6 (python run.py --from-step 6 --to-step 6 --phase <phase>) for a proper TOC.",
        file=sys.stderr,
    )

    # Collect all .md files (excluding _toc placeholder and index-like files)
    from collections import defaultdict
    groups: dict[str, list[Path]] = defaultdict(list)

    for md in sorted(output_dir.rglob("*.md")):
        rel = md.relative_to(output_dir)
        parts = rel.parts
        if len(parts) >= 3:
            group_key = "/".join(parts[:3])  # pub/<product>/<version>
        else:
            group_key = str(rel.parent)
        groups[group_key].append(md)

    nav = []
    for group_key in sorted(groups):
        pages = groups[group_key]
        entries = []
        for page in pages:
            title = page.stem.replace("-", " ").replace("_", " ")
            rel_path = _norm(str(page.relative_to(output_dir)))
            entries.append({title: rel_path})
        if entries:
            nav.append({group_key: entries})

    return nav


def write_hooks_script(hooks_dir: Path) -> Path:
    """Write the frontmatter display hook to hooks_dir/frontmatter_display.py."""
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "frontmatter_display.py"
    hook_path.write_text(_HOOK_SOURCE, encoding="utf-8")
    return hook_path


def write_mkdocs_yml(
    preview_dir: Path,
    output_dir: Path,
    nav: list[dict],
) -> Path:
    """Write preview/mkdocs.yml and return its path."""
    # docs_dir must be relative from preview_dir to output_dir (forward slashes)
    docs_dir_rel = os.path.relpath(output_dir.resolve(), preview_dir.resolve())
    docs_dir_rel = docs_dir_rel.replace("\\", "/")

    config = {
        "site_name": "TIBCO Docs Preview",
        "docs_dir": docs_dir_rel,
        "site_dir": "site",
        "theme": {
            "name": "material",
            "palette": {"scheme": "default", "primary": "indigo"},
            "features": [
                "navigation.tabs",
                "navigation.sections",
                "navigation.expand",
                "navigation.top",
                "search.suggest",
                "search.highlight",
                "content.code.copy",
            ],
        },
        "markdown_extensions": [
            "meta",
            "tables",
            "fenced_code",
            "admonition",
            {"pymdownx.details": None},
            {"pymdownx.superfences": None},
        ],
        "hooks": ["hooks/frontmatter_display.py"],
        "nav": nav,
    }

    # Build YAML manually so markdown_extensions render cleanly
    # (PyYAML serialises {key: None} as "key: null" which MkDocs rejects)
    lines = [
        "# Auto-generated by scripts/preview_html.py — do not edit manually",
        f"site_name: TIBCO Docs Preview",
        f"docs_dir: {docs_dir_rel}",
        "site_dir: site",
        "",
        "theme:",
        "  name: material",
        "  palette:",
        "    scheme: default",
        "    primary: indigo",
        "  features:",
        "    - navigation.tabs",
        "    - navigation.sections",
        "    - navigation.expand",
        "    - navigation.top",
        "    - search.suggest",
        "    - search.highlight",
        "    - content.code.copy",
        "",
        "markdown_extensions:",
        "  - meta",
        "  - tables",
        "  - fenced_code",
        "  - admonition",
        "  - pymdownx.details",
        "  - pymdownx.superfences",
        "",
        "hooks:",
        "  - hooks/frontmatter_display.py",
        "",
    ]

    # Serialize nav using PyYAML (handles nested dicts/lists correctly)
    nav_yaml = yaml.dump({"nav": nav}, allow_unicode=True, default_flow_style=False)
    lines.append(nav_yaml)

    config_path = preview_dir / "mkdocs.yml"
    config_path.write_text("\n".join(lines), encoding="utf-8")
    return config_path


def run_mkdocs(exe: str, config_path: Path, mode: str, port: int) -> int:
    """Run mkdocs in 'serve' or 'build' mode. Returns exit code."""
    cmd = [exe, mode, "--config-file", str(config_path)]
    if mode == "serve":
        cmd += ["--dev-addr", f"127.0.0.1:{port}"]
    # Suppress the flood of link-not-found warnings (broken .htm links, missing
    # images) so the server starts quickly. These are QA artefacts, not errors.
    cmd += ["--no-strict", "-q"]
    print(f"\nRunning: {' '.join(cmd)}\n")
    return subprocess.call(cmd)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a MkDocs preview site from converted Markdown output."
    )
    parser.add_argument(
        "--output-dir", default="output", metavar="PATH",
        help="Root directory of converted .md files (default: output)",
    )
    parser.add_argument(
        "--preview-dir", default="preview", metavar="PATH",
        help="Directory to write mkdocs.yml and hooks into (default: preview)",
    )
    parser.add_argument(
        "--product", action="append", default=[], metavar="SLUG",
        help="Filter by product slug (repeatable). E.g. --product businessevents-enterprise",
    )
    parser.add_argument(
        "--version", default=None, metavar="VER",
        help="Filter by version string. Requires --product.",
    )
    parser.add_argument(
        "--serve", action="store_true", default=False,
        help="Start mkdocs serve with live reload (default action if neither flag given)",
    )
    parser.add_argument(
        "--build", action="store_true", default=False,
        help="Run mkdocs build into preview/site/",
    )
    parser.add_argument(
        "--port", type=int, default=8000, metavar="INT",
        help="Port for mkdocs serve (default: 8000)",
    )
    parser.add_argument(
        "--mkdocs", default=None, metavar="EXE",
        help="Path to mkdocs executable (auto-detected if omitted)",
    )
    args = parser.parse_args()

    # Validate args
    if args.version and not args.product:
        print("ERROR: --version requires --product to be specified.", file=sys.stderr)
        return 1

    # Default to serve if neither --serve nor --build given
    mode = "build" if args.build else "serve"

    output_dir  = Path(args.output_dir).resolve()
    preview_dir = Path(args.preview_dir).resolve()

    if not output_dir.exists():
        print(f"ERROR: output directory not found: {output_dir}", file=sys.stderr)
        return 1

    mkdocs_exe = find_mkdocs_exe(args.mkdocs)

    print(f"\nTIBCO Docs Preview")
    print(f"  Output dir:  {output_dir}")
    print(f"  Preview dir: {preview_dir}")
    print(f"  Mode:        {mode}")
    if args.product:
        print(f"  Products:    {', '.join(args.product)}")
    if args.version:
        print(f"  Version:     {args.version}")

    # 1. Discover _toc.json files
    toc_files = discover_toc_files(output_dir, args.product, args.version)
    print(f"\n  Found {len(toc_files)} _toc.json file(s)")

    # 2. Build nav
    if toc_files:
        nav = build_nav_from_tocs(toc_files, output_dir)
    else:
        nav = build_nav_from_filesystem(output_dir, args.product, args.version)

    if not nav:
        print("ERROR: No pages found to include in the site.", file=sys.stderr)
        return 1

    print(f"  Nav entries: {len(nav)} top-level group(s)")

    # 3. Write generated files
    preview_dir.mkdir(parents=True, exist_ok=True)
    hooks_dir = preview_dir / "hooks"

    hook_path = write_hooks_script(hooks_dir)
    print(f"  Hook written: {hook_path}")

    config_path = write_mkdocs_yml(preview_dir, output_dir, nav)
    print(f"  Config written: {config_path}")

    # 4. Warn about large corpus
    if not args.product and len(toc_files) > 10:
        print(
            f"\n  NOTE: {len(toc_files)} product versions included. "
            "Use --product to filter for faster startup.",
        )

    # 5. Run mkdocs
    if mode == "serve":
        print(f"\n  Starting server at http://127.0.0.1:{args.port}/")
        print("  Press Ctrl+C to stop.\n")
    else:
        print(f"\n  Building static site into {preview_dir / 'site'}/\n")

    return run_mkdocs(mkdocs_exe, config_path, mode, args.port)


if __name__ == "__main__":
    sys.exit(main())
