name: "ActiveSpaces EE"

products:
  # TIBCO ActiveSpaces® - Enterprise Edition
  - https://docs.tibco.com/products/tibco-activespaces-enterprise-edition-5-2-0
  - https://docs.tibco.com/products/tibco-activespaces-enterprise-edition-5-1-1
  - https://docs.tibco.com/products/tibco-activespaces-enterprise-edition-5-1-0
  - https://docs.tibco.com/products/tibco-activespaces-enterprise-edition-5-0-0
  - https://docs.tibco.com/products/tibco-activespaces-enterprise-edition-4-10-1
  - https://docs.tibco.com/products/tibco-activespaces-enterprise-edition-4-10-0
