name: "en-us-ibi-ibi"
products:
  - https://docs.tibco.com/products/ibi-omni-insurance-4-3-0
  - https://docs.tibco.com/products/ibi-data-intelligence-2-0-0
  - https://docs.tibco.com/products/ibi-data-quality-5-2-2
  - https://docs.tibco.com/products/ibi-iway-service-manager-edi-add-on-9-1-1
  - https://docs.tibco.com/products/ibi-mdm-add-on-for-global-data-synchronization-4-0-0
  - https://docs.tibco.com/products/ibi-omni-gen-4-3-0
  - https://docs.tibco.com/products/ibi-omni-healthdata-4-3-0
  - https://docs.tibco.com/products/ibi-open-data-hub-for-mainframe-connectors-1-3-7
  - https://docs.tibco.com/products/ibi-web-query-for-ibm-i-8207-28-14
  - https://docs.tibco.com/products/ibi-webfocus-container-edition-9-3-7
  - https://docs.tibco.com/products/tibco-webfocus-dsml-services-8207-28-0
  - https://docs.tibco.com/products/ibi-webfocus-dsml-services-container-edition-9-3-7
